sudo: false
language: node_js
node_js:
  - '7'
cache:
  directories:
    - wrk/bin
before_script:
  - '[ ! -f wrk/bin/wrk ] && rm -rf wrk && git clone --depth 1 https://github.com/wg/wrk.git && make -j10 -C wrk && mkdir wrk/bin && mv wrk/wrk wrk/bin || true'
  - export PATH=$PWD/wrk/bin:$PATH
script:
  - nvm i 8
  - npm test
  - mv stats.csv 8.csv
  - nvm i 7
  - npm test
  - tail -n +2 8.csv >> stats.csv
after_script:
  - cat stats.csv
