sudo: false
language: node_js
node_js:
  - '14'
cache:
  directories:
    - wrk/bin
before_script:
  - '[ ! -f wrk/bin/wrk ] && rm -rf wrk && git clone --depth 1 https://github.com/wg/wrk.git && make -j10 -C wrk && mkdir wrk/bin && mv wrk/wrk wrk/bin || true'
  - export PATH=$PWD/wrk/bin:$PATH
script:
  - nvm i 14
  - node -p 'process.versions'
  - npm test
  - mv stats.csv 14.csv
  - nvm i 16
  - node -p 'process.versions'
  - npm test
  - mv stats.csv 16.csv
  - nvm i 18
  - node -p 'process.versions'
  - npm test
  - mv stats.csv 18.csv
  - nvm i 19
  - node -p 'process.versions'
  - npm test
  - mv stats.csv 19.csv
